name: Test
on: [push, pull_request]
env:
  SBT_OPTS: "-Dsbt.color=true -Dscala.color=true"
  KAFKA_HOST: kafka:9092
  KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
jobs:
  run-tests:
    name: Run tests
    runs-on: ubuntu-latest
    container: uptane/ci:21-jdk-noble
    services:
      db:
        image: mariadb:10.4
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_USER: libats
          MYSQL_PASSWORD: libats
          MYSQL_DATABASE: libats

      zookeeper:
        image: bitnamilegacy/zookeeper:3.8.1
        ports:
          - 2181:2181
        env:
          ALLOW_ANONYMOUS_LOGIN: yes
        options: >-
          --health-cmd "echo mntr | nc -w 2 -q 2 localhost 2181"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

      kafka:
        image: bitnamilegacy/kafka:2.8.1
        ports:
          - 9092:9092
        options: >-
          --health-cmd "kafka-broker-api-versions.sh --version"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        env:
          KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
          ALLOW_PLAINTEXT_LISTENER: yes
          KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
          KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_ENABLE_KRAFT: "no"

    env:
      DB_URL: "jdbc:mariadb://db:3306/libats"

    steps:
      - uses: actions/checkout@v2
      - name: Coursier cache
        uses: coursier/cache-action@v6
      - run: until mysqladmin ping --protocol=TCP -h db -P 3306 -u root -proot; do echo waiting for mysql; sleep 1; done
      - run: mysql --protocol=TCP --host=db --user=root --port 3306 -proot -e \ GRANT\ ALL\ PRIVILEGES\ ON\ \`libats%\`.\*\ TO\ \'libats\'@\'%\'\;
      - run: sbt test
